// <auto-generated />
using System;
using FUNewsManagementSystem.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FUNewsManagementSystem.Migrations
{
    [DbContext(typeof(FUNewsDbContext))]
    [Migration("20260204022850_AddCreatedByIDToCategoriesAndTags")]
    partial class AddCreatedByIDToCategoriesAndTags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FUNewsManagementSystem.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("AuditLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditLogID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("AuditLogID")
                        .HasName("PK__AuditLog__EB5F6CDD196F5A65");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("FUNewsManagementSystem.Domain.Entities.Category", b =>
                {
                    b.Property<short>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("CategoryID"));

                    b.Property<string>("CategoryDesciption")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<short?>("CreatedByID")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<short?>("ParentCategoryID")
                        .HasColumnType("smallint");

                    b.HasKey("CategoryID");

                    b.HasIndex("ParentCategoryID");

                    b.ToTable("Category", null, t =>
                        {
                            t.HasTrigger("TR_Audit_Category");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("FUNewsManagementSystem.Domain.Entities.NewsArticle", b =>
                {
                    b.Property<string>("NewsArticleID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<short?>("CategoryID")
                        .HasColumnType("smallint");

                    b.Property<short?>("CreatedByID")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("NewsContent")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("NewsSource")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("NewsStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("NewsTitle")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<short?>("UpdatedByID")
                        .HasColumnType("smallint");

                    b.HasKey("NewsArticleID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("CreatedByID");

                    b.ToTable("NewsArticle", null, t =>
                        {
                            t.HasTrigger("TR_Audit_NewsArticle");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("FUNewsManagementSystem.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefreshTokenID"));

                    b.Property<short>("AccountID")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("RefreshTokenID")
                        .HasName("PK__RefreshT__F5845E59A7D510B6");

                    b.HasIndex("AccountID");

                    b.HasIndex(new[] { "Token" }, "IX_RefreshToken_Token");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("FUNewsManagementSystem.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleID")
                        .HasName("PK__Role__8AFACE3A0C2E32F6");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("FUNewsManagementSystem.Domain.Entities.SystemAccount", b =>
                {
                    b.Property<short>("AccountID")
                        .HasColumnType("smallint");

                    b.Property<string>("AccountEmail")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("AccountName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AccountPassword")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("AccountPasswordHash")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("AccountRole")
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GoogleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("AccountID");

                    b.HasIndex("AccountRole");

                    b.ToTable("SystemAccount", null, t =>
                        {
                            t.HasTrigger("TR_Audit_SystemAccount");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("FUNewsManagementSystem.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("TagID")
                        .HasColumnType("int");

                    b.Property<short?>("CreatedByID")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("TagName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TagID")
                        .HasName("PK_HashTag");

                    b.ToTable("Tag", null, t =>
                        {
                            t.HasTrigger("TR_Audit_Tag");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NewsTag", b =>
                {
                    b.Property<string>("NewsArticleID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TagID")
                        .HasColumnType("int");

                    b.HasKey("NewsArticleID", "TagID");

                    b.HasIndex("TagID");

                    b.ToTable("NewsTag", (string)null);
                });

            modelBuilder.Entity("FUNewsManagementSystem.Domain.Entities.Category", b =>
                {
                    b.HasOne("FUNewsManagementSystem.Domain.Entities.Category", "ParentCategory")
                        .WithMany("InverseParentCategory")
                        .HasForeignKey("ParentCategoryID")
                        .HasConstraintName("FK_Category_Category");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("FUNewsManagementSystem.Domain.Entities.NewsArticle", b =>
                {
                    b.HasOne("FUNewsManagementSystem.Domain.Entities.Category", "Category")
                        .WithMany("NewsArticles")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_NewsArticle_Category");

                    b.HasOne("FUNewsManagementSystem.Domain.Entities.SystemAccount", "CreatedBy")
                        .WithMany("NewsArticles")
                        .HasForeignKey("CreatedByID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_NewsArticle_SystemAccount");

                    b.Navigation("Category");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("FUNewsManagementSystem.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("FUNewsManagementSystem.Domain.Entities.SystemAccount", "Account")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AccountID")
                        .IsRequired()
                        .HasConstraintName("FK_RefreshToken_SystemAccount");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("FUNewsManagementSystem.Domain.Entities.SystemAccount", b =>
                {
                    b.HasOne("FUNewsManagementSystem.Domain.Entities.Role", "AccountRoleNavigation")
                        .WithMany("SystemAccounts")
                        .HasForeignKey("AccountRole")
                        .HasConstraintName("FK_SystemAccount_Role");

                    b.Navigation("AccountRoleNavigation");
                });

            modelBuilder.Entity("NewsTag", b =>
                {
                    b.HasOne("FUNewsManagementSystem.Domain.Entities.NewsArticle", null)
                        .WithMany()
                        .HasForeignKey("NewsArticleID")
                        .IsRequired()
                        .HasConstraintName("FK_NewsTag_NewsArticle");

                    b.HasOne("FUNewsManagementSystem.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagID")
                        .IsRequired()
                        .HasConstraintName("FK_NewsTag_Tag");
                });

            modelBuilder.Entity("FUNewsManagementSystem.Domain.Entities.Category", b =>
                {
                    b.Navigation("InverseParentCategory");

                    b.Navigation("NewsArticles");
                });

            modelBuilder.Entity("FUNewsManagementSystem.Domain.Entities.Role", b =>
                {
                    b.Navigation("SystemAccounts");
                });

            modelBuilder.Entity("FUNewsManagementSystem.Domain.Entities.SystemAccount", b =>
                {
                    b.Navigation("NewsArticles");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
